tagFormat: v${version}
plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: angular
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/changelog"
    - preset: angular
      changelogFile: PATH_TO_YOUR_CHANGELOG.MD
  - - "@semantic-release/npm"
    - npmPublish: false
      pkgRoot: Packages/com.artifact.sdk-toolkit
  - - "@semantic-release/git"
    - assets:
        - Packages/com.artifact.sdk-toolkit/package.json
        - Packages/com.artifact.sdk-toolkit/CHANGELOG.md
      message: |-
        chore(release): ${nextRelease.version} [skip ci]

        ${nextRelease.notes}
  - "@semantic-release/github"
