#!/usr/bin/env bash

find . -type f -name "*release*.json" -exec sed -i "s/artifact/$ORGANIZATION_KEBAB/g" {} +
find . -type f -name "*release*.json" -exec sed -i "s/sdk-toolkit/$PACKAGE_KEBAB/g" {} +

cd scripts

find . -type f ! -name "init" -exec sed -i "s/Artifact/$ORGANIZATION_PASCAL/g" {} +
find . -type f ! -name "init" -exec sed -i "s/SdkToolkit/$PACKAGE_PASCAL/g" {} +
find . -type f ! -name "init" -exec sed -i "s/artifact/$ORGANIZATION_KEBAB/g" {} +
find . -type f ! -name "init" -exec sed -i "s/sdk-toolkit/$PACKAGE_KEBAB/g" {} +

cd -

cd Packages

find . -type f -name "*.json" -exec sed -i "s/artifact/$ORGANIZATION_KEBAB/g" {} +
find . -type f -name "*.json" -exec sed -i "s/sdk-toolkit/$PACKAGE_KEBAB/g" {} +
find . -type f -name "*.json" -exec sed -i "s/SdkToolkit/$PACKAGE_PASCAL/g" {} +

find . -type f -name "*.cs" -exec sed -i "s/Artifact/$ORGANIZATION_PASCAL/g" {} +
find . -type f -name "*.cs" -exec sed -i "s/SdkToolkit/$PACKAGE_PASCAL/g" {} +
find . -type f -name "*.asmdef" -exec sed -i "s/Artifact/$ORGANIZATION_PASCAL/g" {} +
find . -type f -name "*.asmdef" -exec sed -i "s/SdkToolkit/$PACKAGE_PASCAL/g" {} +
find . -type f -name "*.md" -exec sed -i "s/Artifact/$ORGANIZATION_PASCAL/g" {} +
find . -type f -name "*.md" -exec sed -i "s/SdkToolkit/$PACKAGE_PASCAL/g" {} +

find . -type f -name "*.asmdef" -exec bash -c 'mv "$2" "${2/Artifact/$1}"' -- ${ORGANIZATION_PASCAL} {} \;
find . -type f -name "*.asmdef" -exec bash -c 'mv "$2" "${2/SdkToolkit/$1}"' -- ${PACKAGE_PASCAL} {} \;
find . -type f -name "*.asmdef.meta" -exec bash -c 'mv "$2" "${2/Artifact/$1}"' -- ${ORGANIZATION_PASCAL} {} \;
find . -type f -name "*.asmdef.meta" -exec bash -c 'mv "$2" "${2/SdkToolkit/$1}"' -- ${PACKAGE_PASCAL} {} \;
find . -type f -name "*.md" -exec bash -c 'mv "$2" "${2/Artifact/$1}"' -- ${ORGANIZATION_PASCAL} {} \;
find . -type f -name "*.md" -exec bash -c 'mv "$2" "${2/SdkToolkit/$1}"' -- ${PACKAGE_PASCAL} {} \;
find . -type f -name "*.md.meta" -exec bash -c 'mv "$2" "${2/Artifact/$1}"' -- ${ORGANIZATION_PASCAL} {} \;
find . -type f -name "*.md.meta" -exec bash -c 'mv "$2" "${2/SdkToolkit/$1}"' -- ${PACKAGE_PASCAL} {} \;

mv com.artifact.sdk-toolkit com.${ORGANIZATION_KEBAB}.${PACKAGE_KEBAB}

cd -

cd ProjectSettings

sed -i "s/companyName: DefaultCompany/companyName: $ORGANIZATION_PASCAL/" ProjectSettings.asset
sed -i "s/productName: UPMTemplate/productName: $PACKAGE_PASCAL/" ProjectSettings.asset

cd -
